<?php
$title = 'Authentification';
$this->headTitle($title);
?>

<?php
$form->setAttribute('action', $this->url('admin', array('action' => 'login')));
$form->setAttribute('role', 'form');
$form->prepare();
?>
<?php

if (isset($_GET['status']) && $_GET['status']=="u_login" ) {
  echo '<div class="card-panel red lighten-2">vous devez dabord vous connecter</div>';
}
if (isset($_GET['status']) && $_GET['status']=="filed_login" ) {
  echo '<div class="card-panel red lighten-2">e-mail ou mot de passe ne sont pas correctes, essayez à nouveau</div>';
}

?>
<div class="row">
  <div class="col  s12 m12 l4">.</div>
  <div class="col  s12 m12 l4">
    <div class="card small z-depth-2  " id="log" style="height:auto; border-radius:10px;">

        <div class="row">
        <div style="width:100%;height:auto;padding:3px;margin:auto;background-color:teal;color:white" class=" center down col s12 m12 l12">
          <h5>Admin</h5>    
          <i class="material-icons large">perm_identity</i>
        </div>
        </div>

      <?php echo $this->form()->openTag($form);  ?>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">email</i>
            <?php echo $this->formRow($form->get('email'));  ?>
            <label for="email">Email</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix">vpn_key</i>
            <?php echo $this->formRow($form->get('password'));  ?>
            <label for="password">Password</label>
          </div>
         
        </div>
        <div class="row">
          <div class="col s4 m4 l4">.</div>
          <div class="col s4 m4 l4">
            <?php echo $this->formSubmit($form->get('submit'));  ?>
          </div>
          <div class="col s4 m4 l4">.</div>
          <br/><br/><br/>
        
        </div>
      <?php echo $this->form()->closeTag();  ?>
    </div>
   </div>
  <div class="col  s12 m12 l4">.</div>
  </div>




   <script type="text/javascript" charset="utf-8" >
var options = [ {selector: '.row', offset: 50, callback: 'Materialize.toast("Salut, vous devez vous identifier", 7000 )' }];
    Materialize.scrollFire(options); 
   </script>
